kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  namespace: af-connect-cicd
  name: af-connect-outbox
  labels:
    build: af-connect-outbox
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
spec:
  runPolicy: "Serial"
  nodeSelector: {}
  triggers: []
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: REDIS_HOST
          value: redis-db
  output:
    to:
      kind: ImageStreamTag
      name: 'af-connect-outbox:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/MagnumOpuses/af-connect-outbox.git'
      ref: jenkins/deploy