apiVersion: v1
kind: Service
metadata:
    name: af-connect-outbox
spec:
    ports:
        - name: http
          port: 8100
          protocol: TCP
          targetPort: 8100
    selector:
        deploymentconfig: af-connect-outbox
    type: ClusterIP