//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AffiliatedOrganizationTypeCodeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AffiliatedOrganizationTypeCodeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Professional"/>
 *     &lt;enumeration value="Social"/>
 *     &lt;enumeration value="Community"/>
 *     &lt;enumeration value="Non-profit"/>
 *     &lt;enumeration value="Religious"/>
 *     &lt;enumeration value="Political"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AffiliatedOrganizationTypeCodeList")
@XmlEnum
public enum AffiliatedOrganizationTypeCodeList {


    /**
     * Professional
     * 
     */
    @XmlEnumValue("Professional")
    PROFESSIONAL("Professional"),

    /**
     * Social
     * 
     */
    @XmlEnumValue("Social")
    SOCIAL("Social"),

    /**
     * Community
     * 
     */
    @XmlEnumValue("Community")
    COMMUNITY("Community"),

    /**
     * Non-profit
     * 
     */
    @XmlEnumValue("Non-profit")
    NON_PROFIT("Non-profit"),

    /**
     * Religious
     * 
     */
    @XmlEnumValue("Religious")
    RELIGIOUS("Religious"),

    /**
     * Political
     * 
     */
    @XmlEnumValue("Political")
    POLITICAL("Political");
    private final String value;

    AffiliatedOrganizationTypeCodeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AffiliatedOrganizationTypeCodeList fromValue(String v) {
        for (AffiliatedOrganizationTypeCodeList c: AffiliatedOrganizationTypeCodeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
