//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EducationDegreeGrantedStatusCodeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EducationDegreeGrantedStatusCodeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Granted"/>
 *     &lt;enumeration value="InProgress"/>
 *     &lt;enumeration value="Postponed"/>
 *     &lt;enumeration value="NotGranted"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EducationDegreeGrantedStatusCodeList")
@XmlEnum
public enum EducationDegreeGrantedStatusCodeList {


    /**
     * Granted
     * 
     */
    @XmlEnumValue("Granted")
    GRANTED("Granted"),

    /**
     * In Progress
     * 
     */
    @XmlEnumValue("InProgress")
    IN_PROGRESS("InProgress"),

    /**
     * Postponed
     * 
     */
    @XmlEnumValue("Postponed")
    POSTPONED("Postponed"),

    /**
     * Not Granted
     * 
     */
    @XmlEnumValue("NotGranted")
    NOT_GRANTED("NotGranted");
    private final String value;

    EducationDegreeGrantedStatusCodeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EducationDegreeGrantedStatusCodeList fromValue(String v) {
        for (EducationDegreeGrantedStatusCodeList c: EducationDegreeGrantedStatusCodeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
