//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicenseType", propOrder = {

})
public class LicenseType {

    public IdentifierType id;
    public String name;
    public EntityType type;
    public String status;
    public EffectiveTimePeriodType effectiveTimePeriod;
    public String issued;
    public String firstIssued;
    public OrganizationType issuingAuthority;
    public List<AttachmentReferenceType> attachmentReferences;
    public List<String> descriptions;
    public Endorsements endorsements;
    public Restrictions restrictions;
    public Violations violations;

    public IdentifierType getId() {
        return id;
    }

    public void setId(IdentifierType id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public EntityType getType() {
        return type;
    }

    public void setType(EntityType type) {
        this.type = type;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public EffectiveTimePeriodType getEffectiveTimePeriod() {
        return effectiveTimePeriod;
    }

    public void setEffectiveTimePeriod(EffectiveTimePeriodType effectiveTimePeriod) {
        this.effectiveTimePeriod = effectiveTimePeriod;
    }

    public String getIssued() {
        return issued;
    }

    public void setIssued(String issued) {
        this.issued = issued;
    }

    public String getFirstIssued() {
        return firstIssued;
    }

    public void setFirstIssued(String firstIssued) {
        this.firstIssued = firstIssued;
    }

    public OrganizationType getIssuingAuthority() {
        return issuingAuthority;
    }

    public void setIssuingAuthority(OrganizationType issuingAuthority) {
        this.issuingAuthority = issuingAuthority;
    }

    public List<AttachmentReferenceType> getAttachmentReferences() {
        if (attachmentReferences == null) {
            attachmentReferences = new ArrayList<AttachmentReferenceType>();
        }
        return this.attachmentReferences;
    }

    public void setAttachmentReferences(List<AttachmentReferenceType> attachmentReferences) {
        this.attachmentReferences = attachmentReferences;
    }

    public List<String> getDescriptions() {
        if (descriptions == null) {
            descriptions = new ArrayList<String>();
        }
        return this.descriptions;
    }

    public void setDescriptions(List<String> descriptions) {
        this.descriptions = descriptions;
    }

    public Endorsements getEndorsements() {
        return endorsements;
    }

    public void setEndorsements(Endorsements endorsements) {
        this.endorsements = endorsements;
    }

    public Restrictions getRestrictions() {
        return restrictions;
    }

    public void setRestrictions(Restrictions restrictions) {
        this.restrictions = restrictions;
    }

    public Violations getViolations() {
        return violations;
    }

    public void setViolations(Violations violations) {
        this.violations = violations;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Endorsements {

        @XmlElement(required = true)
        protected List<Item> item;


        public List<Item> getItem() {
            if (item == null) {
                item = new ArrayList<Item>();
            }
            return this.item;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Item {

            protected XMLGregorianCalendar validFrom;
            protected XMLGregorianCalendar validTo;
            @XmlElement(required = true)
            protected String value;
            protected String description;

            public XMLGregorianCalendar getValidFrom() {
                return validFrom;
            }

            public void setValidFrom(XMLGregorianCalendar validFrom) {
                this.validFrom = validFrom;
            }

            public XMLGregorianCalendar getValidTo() {
                return validTo;
            }

            public void setValidTo(XMLGregorianCalendar validTo) {
                this.validTo = validTo;
            }

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String description) {
                this.description = description;
            }
        }

    }



    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Restrictions {

        @XmlElement(required = true)
        protected List<Item> item;

        public List<Item> getItem() {
            if (item == null) {
                item = new ArrayList<Item>();
            }
            return this.item;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Item {

            protected XMLGregorianCalendar validFrom;
            protected XMLGregorianCalendar validTo;
            @XmlElement(required = true)
            protected String value;
            protected String description;

            public XMLGregorianCalendar getValidFrom() {
                return validFrom;
            }

            public void setValidFrom(XMLGregorianCalendar validFrom) {
                this.validFrom = validFrom;
            }

            public XMLGregorianCalendar getValidTo() {
                return validTo;
            }

            public void setValidTo(XMLGregorianCalendar validTo) {
                this.validTo = validTo;
            }

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String description) {
                this.description = description;
            }
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Violations {

        @XmlElement(required = true)
        protected List<Item> item;


        public List<Item> getItem() {
            if (item == null) {
                item = new ArrayList<Item>();
            }
            return this.item;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Item {

            protected XMLGregorianCalendar validFrom;
            protected XMLGregorianCalendar validTo;
            @XmlElement(required = true)
            protected String value;
            protected String description;

            public XMLGregorianCalendar getValidFrom() {
                return validFrom;
            }

            public void setValidFrom(XMLGregorianCalendar validFrom) {
                this.validFrom = validFrom;
            }

            public XMLGregorianCalendar getValidTo() {
                return validTo;
            }

            public void setValidTo(XMLGregorianCalendar validTo) {
                this.validTo = validTo;
            }

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String description) {
                this.description = description;
            }
        }

    }

}
