//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://hropenstandards.org/schema/xml/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.arbetsformedlingen.matchning.portability.dto;
