//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Single date/timespan/month/year or period between two dates/months/years.
 * 
 * <p>Java class for PeriodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{https://hropenstandards.org/schema/xml/}FormattedDateTime"/>
 *         &lt;element ref="{https://hropenstandards.org/schema/xml/}DateTimePeriod"/>
 *         &lt;element ref="{https://hropenstandards.org/schema/xml/}DatePeriod"/>
 *         &lt;element ref="{https://hropenstandards.org/schema/xml/}YearMonthPeriod"/>
 *         &lt;element ref="{https://hropenstandards.org/schema/xml/}YearPeriod"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodType", propOrder = {
    "formattedDateTime",
    "dateTimePeriod",
    "datePeriod",
    "yearMonthPeriod",
    "yearPeriod"
})
public class PeriodType {

    @XmlElement(name = "FormattedDateTime")
    protected String formattedDateTime;
    @XmlElement(name = "DateTimePeriod")
    protected DateTimePeriodType dateTimePeriod;
    @XmlElement(name = "DatePeriod")
    protected DatePeriodType datePeriod;
    @XmlElement(name = "YearMonthPeriod")
    protected YearMonthPeriodType yearMonthPeriod;
    @XmlElement(name = "YearPeriod")
    protected YearPeriodType yearPeriod;

    /**
     * Gets the value of the formattedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedDateTime() {
        return formattedDateTime;
    }

    /**
     * Sets the value of the formattedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedDateTime(String value) {
        this.formattedDateTime = value;
    }

    /**
     * Gets the value of the dateTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimePeriodType }
     *     
     */
    public DateTimePeriodType getDateTimePeriod() {
        return dateTimePeriod;
    }

    /**
     * Sets the value of the dateTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimePeriodType }
     *     
     */
    public void setDateTimePeriod(DateTimePeriodType value) {
        this.dateTimePeriod = value;
    }

    /**
     * Gets the value of the datePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link DatePeriodType }
     *     
     */
    public DatePeriodType getDatePeriod() {
        return datePeriod;
    }

    /**
     * Sets the value of the datePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatePeriodType }
     *     
     */
    public void setDatePeriod(DatePeriodType value) {
        this.datePeriod = value;
    }

    /**
     * Gets the value of the yearMonthPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link YearMonthPeriodType }
     *     
     */
    public YearMonthPeriodType getYearMonthPeriod() {
        return yearMonthPeriod;
    }

    /**
     * Sets the value of the yearMonthPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearMonthPeriodType }
     *     
     */
    public void setYearMonthPeriod(YearMonthPeriodType value) {
        this.yearMonthPeriod = value;
    }

    /**
     * Gets the value of the yearPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link YearPeriodType }
     *     
     */
    public YearPeriodType getYearPeriod() {
        return yearPeriod;
    }

    /**
     * Sets the value of the yearPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link YearPeriodType }
     *     
     */
    public void setYearPeriod(YearPeriodType value) {
        this.yearPeriod = value;
    }

}
