//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A specified person competency is a competency within the context of a personal record (profile, appraisal, assessment) assessed or asserted at specified level of proficiency.
 * 
 * <p>Java class for PersonCompetencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonCompetencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="competencyIds" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="competencyName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="description" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="proficiencyLevel" type="{https://hropenstandards.org/schema/xml/}BaseScoreType" minOccurs="0"/>
 *         &lt;element name="lastUsedDate" type="{https://hropenstandards.org/schema/xml/}FormattedDateTimeType" minOccurs="0"/>
 *         &lt;element name="experienceMeasure" type="{https://hropenstandards.org/schema/xml/}MeasureType" minOccurs="0"/>
 *         &lt;element name="interestLevel" type="{https://hropenstandards.org/schema/xml/}BaseScoreType" minOccurs="0"/>
 *         &lt;element name="competencyDimensions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}CompetencyDimensionType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="competencyEvidence" type="{https://hropenstandards.org/schema/xml/}CompetencyEvidenceType" minOccurs="0"/>
 *         &lt;element name="attachmentReferences" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}AttachmentReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonCompetencyType", propOrder = {

})
public class PersonCompetencyType {

    protected CompetencyIds competencyIds;
    protected String competencyName;
    protected String description;
    protected BaseScoreType proficiencyLevel;
    protected String lastUsedDate;
    protected MeasureType experienceMeasure;
    protected BaseScoreType interestLevel;
    protected CompetencyDimensions competencyDimensions;
    protected CompetencyEvidenceType competencyEvidence;
    protected AttachmentReferences attachmentReferences;

    /**
     * Gets the value of the competencyIds property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyIds }
     *     
     */
    public CompetencyIds getCompetencyIds() {
        return competencyIds;
    }

    /**
     * Sets the value of the competencyIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyIds }
     *     
     */
    public void setCompetencyIds(CompetencyIds value) {
        this.competencyIds = value;
    }

    /**
     * Gets the value of the competencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompetencyName() {
        return competencyName;
    }

    /**
     * Sets the value of the competencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompetencyName(String value) {
        this.competencyName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the proficiencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BaseScoreType }
     *     
     */
    public BaseScoreType getProficiencyLevel() {
        return proficiencyLevel;
    }

    /**
     * Sets the value of the proficiencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseScoreType }
     *     
     */
    public void setProficiencyLevel(BaseScoreType value) {
        this.proficiencyLevel = value;
    }

    /**
     * Gets the value of the lastUsedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUsedDate() {
        return lastUsedDate;
    }

    /**
     * Sets the value of the lastUsedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUsedDate(String value) {
        this.lastUsedDate = value;
    }

    /**
     * Gets the value of the experienceMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType }
     *     
     */
    public MeasureType getExperienceMeasure() {
        return experienceMeasure;
    }

    /**
     * Sets the value of the experienceMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType }
     *     
     */
    public void setExperienceMeasure(MeasureType value) {
        this.experienceMeasure = value;
    }

    /**
     * Gets the value of the interestLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BaseScoreType }
     *     
     */
    public BaseScoreType getInterestLevel() {
        return interestLevel;
    }

    /**
     * Sets the value of the interestLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseScoreType }
     *     
     */
    public void setInterestLevel(BaseScoreType value) {
        this.interestLevel = value;
    }

    /**
     * Gets the value of the competencyDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyDimensions }
     *     
     */
    public CompetencyDimensions getCompetencyDimensions() {
        return competencyDimensions;
    }

    /**
     * Sets the value of the competencyDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyDimensions }
     *     
     */
    public void setCompetencyDimensions(CompetencyDimensions value) {
        this.competencyDimensions = value;
    }

    /**
     * Gets the value of the competencyEvidence property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyEvidenceType }
     *     
     */
    public CompetencyEvidenceType getCompetencyEvidence() {
        return competencyEvidence;
    }

    /**
     * Sets the value of the competencyEvidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyEvidenceType }
     *     
     */
    public void setCompetencyEvidence(CompetencyEvidenceType value) {
        this.competencyEvidence = value;
    }

    /**
     * Gets the value of the attachmentReferences property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentReferences }
     *     
     */
    public AttachmentReferences getAttachmentReferences() {
        return attachmentReferences;
    }

    /**
     * Sets the value of the attachmentReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentReferences }
     *     
     */
    public void setAttachmentReferences(AttachmentReferences value) {
        this.attachmentReferences = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}AttachmentReferenceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class AttachmentReferences {

        protected List<AttachmentReferenceType> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttachmentReferenceType }
         * 
         * 
         */
        public List<AttachmentReferenceType> getItem() {
            if (item == null) {
                item = new ArrayList<AttachmentReferenceType>();
            }
            return this.item;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}CompetencyDimensionType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class CompetencyDimensions {

        protected List<CompetencyDimensionType> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompetencyDimensionType }
         * 
         * 
         */
        public List<CompetencyDimensionType> getItem() {
            if (item == null) {
                item = new ArrayList<CompetencyDimensionType>();
            }
            return this.item;
        }

    }


    /**
     * A unique identifier for a competency definition.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}IdentifierType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class CompetencyIds {

        protected List<IdentifierType> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IdentifierType }
         * 
         * 
         */
        public List<IdentifierType> getItem() {
            if (item == null) {
                item = new ArrayList<IdentifierType>();
            }
            return this.item;
        }

    }

}
