//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Provides recruiting and staffing key date information.
 * 
 * <p>Java class for RecruitingAndStaffingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecruitingAndStaffingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="applicationDate" type="{https://hropenstandards.org/schema/xml/}DateType" minOccurs="0"/>
 *         &lt;element name="interviewDates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}DateType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rejectionDate" type="{https://hropenstandards.org/schema/xml/}DateType" minOccurs="0"/>
 *         &lt;element name="rejectionReasonCode" type="{https://hropenstandards.org/schema/xml/}CodeType" minOccurs="0"/>
 *         &lt;element name="offeredOnDate" type="{https://hropenstandards.org/schema/xml/}DateType" minOccurs="0"/>
 *         &lt;element name="offerAcceptedDate" type="{https://hropenstandards.org/schema/xml/}DateType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecruitingAndStaffingType", propOrder = {

})
public class RecruitingAndStaffingType {

    protected XMLGregorianCalendar applicationDate;
    protected InterviewDates interviewDates;
    protected XMLGregorianCalendar rejectionDate;
    protected String rejectionReasonCode;
    protected XMLGregorianCalendar offeredOnDate;
    protected XMLGregorianCalendar offerAcceptedDate;

    /**
     * Gets the value of the applicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplicationDate() {
        return applicationDate;
    }

    /**
     * Sets the value of the applicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplicationDate(XMLGregorianCalendar value) {
        this.applicationDate = value;
    }

    /**
     * Gets the value of the interviewDates property.
     * 
     * @return
     *     possible object is
     *     {@link InterviewDates }
     *     
     */
    public InterviewDates getInterviewDates() {
        return interviewDates;
    }

    /**
     * Sets the value of the interviewDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterviewDates }
     *     
     */
    public void setInterviewDates(InterviewDates value) {
        this.interviewDates = value;
    }

    /**
     * Gets the value of the rejectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRejectionDate() {
        return rejectionDate;
    }

    /**
     * Sets the value of the rejectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRejectionDate(XMLGregorianCalendar value) {
        this.rejectionDate = value;
    }

    /**
     * Gets the value of the rejectionReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectionReasonCode() {
        return rejectionReasonCode;
    }

    /**
     * Sets the value of the rejectionReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectionReasonCode(String value) {
        this.rejectionReasonCode = value;
    }

    /**
     * Gets the value of the offeredOnDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferedOnDate() {
        return offeredOnDate;
    }

    /**
     * Sets the value of the offeredOnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferedOnDate(XMLGregorianCalendar value) {
        this.offeredOnDate = value;
    }

    /**
     * Gets the value of the offerAcceptedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferAcceptedDate() {
        return offerAcceptedDate;
    }

    /**
     * Sets the value of the offerAcceptedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferAcceptedDate(XMLGregorianCalendar value) {
        this.offerAcceptedDate = value;
    }


    /**
     * The date(s) of interview(s).
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" type="{https://hropenstandards.org/schema/xml/}DateType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class InterviewDates {

        protected List<XMLGregorianCalendar> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMLGregorianCalendar }
         * 
         * 
         */
        public List<XMLGregorianCalendar> getItem() {
            if (item == null) {
                item = new ArrayList<XMLGregorianCalendar>();
            }
            return this.item;
        }

    }

}
