//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The minimum and maximum range of work compensation.
 * 
 * <p>Java class for RemunerationRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemunerationRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="typeCode" type="{https://hropenstandards.org/schema/xml/}PayTypeCodeList" minOccurs="0"/>
 *         &lt;element name="referenceAmount" type="{https://hropenstandards.org/schema/xml/}AmountType" minOccurs="0"/>
 *         &lt;element name="minimumAmount" type="{https://hropenstandards.org/schema/xml/}AmountType" minOccurs="0"/>
 *         &lt;element name="maximumAmount" type="{https://hropenstandards.org/schema/xml/}AmountType" minOccurs="0"/>
 *         &lt;element name="intervalCode" type="{https://hropenstandards.org/schema/xml/}PayRateIntervalCodeList" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemunerationRangeType", propOrder = {

})
public class RemunerationRangeType {

    protected PayTypeCodeList typeCode;
    protected AmountType referenceAmount;
    protected AmountType minimumAmount;
    protected AmountType maximumAmount;
    protected PayRateIntervalCodeList intervalCode;

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link PayTypeCodeList }
     *     
     */
    public PayTypeCodeList getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayTypeCodeList }
     *     
     */
    public void setTypeCode(PayTypeCodeList value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the referenceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getReferenceAmount() {
        return referenceAmount;
    }

    /**
     * Sets the value of the referenceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setReferenceAmount(AmountType value) {
        this.referenceAmount = value;
    }

    /**
     * Gets the value of the minimumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getMinimumAmount() {
        return minimumAmount;
    }

    /**
     * Sets the value of the minimumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setMinimumAmount(AmountType value) {
        this.minimumAmount = value;
    }

    /**
     * Gets the value of the maximumAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getMaximumAmount() {
        return maximumAmount;
    }

    /**
     * Sets the value of the maximumAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setMaximumAmount(AmountType value) {
        this.maximumAmount = value;
    }

    /**
     * Gets the value of the intervalCode property.
     * 
     * @return
     *     possible object is
     *     {@link PayRateIntervalCodeList }
     *     
     */
    public PayRateIntervalCodeList getIntervalCode() {
        return intervalCode;
    }

    /**
     * Sets the value of the intervalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayRateIntervalCodeList }
     *     
     */
    public void setIntervalCode(PayRateIntervalCodeList value) {
        this.intervalCode = value;
    }

}
