//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponsibilityCodeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponsibilityCodeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unit"/>
 *     &lt;enumeration value="Department"/>
 *     &lt;enumeration value="Division"/>
 *     &lt;enumeration value="Parent"/>
 *     &lt;enumeration value="Group"/>
 *     &lt;enumeration value="Plant"/>
 *     &lt;enumeration value="Subsidiary"/>
 *     &lt;enumeration value="Joint Venture"/>
 *     &lt;enumeration value="Branch"/>
 *     &lt;enumeration value="Holding Affiliate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResponsibilityCodeList")
@XmlEnum
public enum ResponsibilityCodeList {

    @XmlEnumValue("Unit")
    UNIT("Unit"),
    @XmlEnumValue("Department")
    DEPARTMENT("Department"),
    @XmlEnumValue("Division")
    DIVISION("Division"),
    @XmlEnumValue("Parent")
    PARENT("Parent"),
    @XmlEnumValue("Group")
    GROUP("Group"),
    @XmlEnumValue("Plant")
    PLANT("Plant"),
    @XmlEnumValue("Subsidiary")
    SUBSIDIARY("Subsidiary"),
    @XmlEnumValue("Joint Venture")
    JOINT_VENTURE("Joint Venture"),
    @XmlEnumValue("Branch")
    BRANCH("Branch"),
    @XmlEnumValue("Holding Affiliate")
    HOLDING_AFFILIATE("Holding Affiliate");
    private final String value;

    ResponsibilityCodeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResponsibilityCodeList fromValue(String v) {
        for (ResponsibilityCodeList c: ResponsibilityCodeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
