//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 05:13:24 PM CEST 
//


package se.arbetsformedlingen.matchning.portability.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityPermissionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityPermissionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Read"/>
 *     &lt;enumeration value="Modify"/>
 *     &lt;enumeration value="Store"/>
 *     &lt;enumeration value="Full Control"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecurityPermissionType")
@XmlEnum
public enum SecurityPermissionType {

    @XmlEnumValue("Read")
    READ("Read"),
    @XmlEnumValue("Modify")
    MODIFY("Modify"),
    @XmlEnumValue("Store")
    STORE("Store"),
    @XmlEnumValue("Full Control")
    FULL_CONTROL("Full Control");
    private final String value;

    SecurityPermissionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SecurityPermissionType fromValue(String v) {
        for (SecurityPermissionType c: SecurityPermissionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
